// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: pocketuniverserpc/pocketuniverse.proto

package pocketuniverserpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComputeSigHashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The funded virtual PSBT
	FundedPsbt []byte `protobuf:"bytes,1,opt,name=funded_psbt,json=fundedPsbt,proto3" json:"funded_psbt,omitempty"`
}

func (x *ComputeSigHashRequest) Reset() {
	*x = ComputeSigHashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pocketuniverserpc_pocketuniverse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComputeSigHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeSigHashRequest) ProtoMessage() {}

func (x *ComputeSigHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pocketuniverserpc_pocketuniverse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeSigHashRequest.ProtoReflect.Descriptor instead.
func (*ComputeSigHashRequest) Descriptor() ([]byte, []int) {
	return file_pocketuniverserpc_pocketuniverse_proto_rawDescGZIP(), []int{0}
}

func (x *ComputeSigHashRequest) GetFundedPsbt() []byte {
	if x != nil {
		return x.FundedPsbt
	}
	return nil
}

type ComputeSigHashResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The sighashes that need to be signed, one per input
	Sighashes [][]byte `protobuf:"bytes,1,rep,name=sighashes,proto3" json:"sighashes,omitempty"`
}

func (x *ComputeSigHashResponse) Reset() {
	*x = ComputeSigHashResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pocketuniverserpc_pocketuniverse_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComputeSigHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeSigHashResponse) ProtoMessage() {}

func (x *ComputeSigHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pocketuniverserpc_pocketuniverse_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeSigHashResponse.ProtoReflect.Descriptor instead.
func (*ComputeSigHashResponse) Descriptor() ([]byte, []int) {
	return file_pocketuniverserpc_pocketuniverse_proto_rawDescGZIP(), []int{1}
}

func (x *ComputeSigHashResponse) GetSighashes() [][]byte {
	if x != nil {
		return x.Sighashes
	}
	return nil
}

type ApplyExternalSigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The funded virtual PSBT
	FundedPsbt []byte `protobuf:"bytes,1,opt,name=funded_psbt,json=fundedPsbt,proto3" json:"funded_psbt,omitempty"`
	// The schnorr signatures, one per input
	Signatures [][]byte `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
}

func (x *ApplyExternalSigRequest) Reset() {
	*x = ApplyExternalSigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pocketuniverserpc_pocketuniverse_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyExternalSigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyExternalSigRequest) ProtoMessage() {}

func (x *ApplyExternalSigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pocketuniverserpc_pocketuniverse_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyExternalSigRequest.ProtoReflect.Descriptor instead.
func (*ApplyExternalSigRequest) Descriptor() ([]byte, []int) {
	return file_pocketuniverserpc_pocketuniverse_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyExternalSigRequest) GetFundedPsbt() []byte {
	if x != nil {
		return x.FundedPsbt
	}
	return nil
}

func (x *ApplyExternalSigRequest) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type ApplyExternalSigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The signed virtual PSBT
	SignedPsbt []byte `protobuf:"bytes,1,opt,name=signed_psbt,json=signedPsbt,proto3" json:"signed_psbt,omitempty"`
	// The indices of signed inputs
	SignedInputs []uint32 `protobuf:"varint,2,rep,packed,name=signed_inputs,json=signedInputs,proto3" json:"signed_inputs,omitempty"`
}

func (x *ApplyExternalSigResponse) Reset() {
	*x = ApplyExternalSigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pocketuniverserpc_pocketuniverse_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyExternalSigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyExternalSigResponse) ProtoMessage() {}

func (x *ApplyExternalSigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pocketuniverserpc_pocketuniverse_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyExternalSigResponse.ProtoReflect.Descriptor instead.
func (*ApplyExternalSigResponse) Descriptor() ([]byte, []int) {
	return file_pocketuniverserpc_pocketuniverse_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyExternalSigResponse) GetSignedPsbt() []byte {
	if x != nil {
		return x.SignedPsbt
	}
	return nil
}

func (x *ApplyExternalSigResponse) GetSignedInputs() []uint32 {
	if x != nil {
		return x.SignedInputs
	}
	return nil
}

var File_pocketuniverserpc_pocketuniverse_proto protoreflect.FileDescriptor

var file_pocketuniverserpc_pocketuniverse_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x70, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65, 0x72, 0x70, 0x63, 0x22, 0x38, 0x0a, 0x15, 0x43,
	0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x53, 0x69, 0x67, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x75, 0x6e, 0x64, 0x65, 0x64, 0x5f, 0x70,
	0x73, 0x62, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x66, 0x75, 0x6e, 0x64, 0x65,
	0x64, 0x50, 0x73, 0x62, 0x74, 0x22, 0x36, 0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65,
	0x53, 0x69, 0x67, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x22, 0x5a, 0x0a,
	0x17, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x69,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x75, 0x6e, 0x64,
	0x65, 0x64, 0x5f, 0x70, 0x73, 0x62, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x66,
	0x75, 0x6e, 0x64, 0x65, 0x64, 0x50, 0x73, 0x62, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x60, 0x0a, 0x18, 0x41, 0x70, 0x70,
	0x6c, 0x79, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f,
	0x70, 0x73, 0x62, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x64, 0x50, 0x73, 0x62, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64,
	0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0c, 0x73,
	0x69, 0x67, 0x6e, 0x65, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x32, 0xf3, 0x01, 0x0a, 0x0e,
	0x50, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65, 0x12, 0x6e,
	0x0a, 0x17, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c,
	0x54, 0x78, 0x53, 0x69, 0x67, 0x48, 0x61, 0x73, 0x68, 0x12, 0x28, 0x2e, 0x70, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f,
	0x6d, 0x70, 0x75, 0x74, 0x65, 0x53, 0x69, 0x67, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x70, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x75, 0x6e, 0x69, 0x76,
	0x65, 0x72, 0x73, 0x65, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x53,
	0x69, 0x67, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x71,
	0x0a, 0x16, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2a, 0x2e, 0x70, 0x6f, 0x63, 0x6b, 0x65,
	0x74, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x70, 0x70,
	0x6c, 0x79, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x70, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x75, 0x6e, 0x69,
	0x76, 0x65, 0x72, 0x73, 0x65, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x45, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x69, 0x6e, 0x67, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x74, 0x61,
	0x70, 0x72, 0x6f, 0x6f, 0x74, 0x2d, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x74, 0x61, 0x70,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72,
	0x73, 0x65, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pocketuniverserpc_pocketuniverse_proto_rawDescOnce sync.Once
	file_pocketuniverserpc_pocketuniverse_proto_rawDescData = file_pocketuniverserpc_pocketuniverse_proto_rawDesc
)

func file_pocketuniverserpc_pocketuniverse_proto_rawDescGZIP() []byte {
	file_pocketuniverserpc_pocketuniverse_proto_rawDescOnce.Do(func() {
		file_pocketuniverserpc_pocketuniverse_proto_rawDescData = protoimpl.X.CompressGZIP(file_pocketuniverserpc_pocketuniverse_proto_rawDescData)
	})
	return file_pocketuniverserpc_pocketuniverse_proto_rawDescData
}

var file_pocketuniverserpc_pocketuniverse_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pocketuniverserpc_pocketuniverse_proto_goTypes = []any{
	(*ComputeSigHashRequest)(nil),    // 0: pocketuniverserpc.ComputeSigHashRequest
	(*ComputeSigHashResponse)(nil),   // 1: pocketuniverserpc.ComputeSigHashResponse
	(*ApplyExternalSigRequest)(nil),  // 2: pocketuniverserpc.ApplyExternalSigRequest
	(*ApplyExternalSigResponse)(nil), // 3: pocketuniverserpc.ApplyExternalSigResponse
}
var file_pocketuniverserpc_pocketuniverse_proto_depIdxs = []int32{
	0, // 0: pocketuniverserpc.PocketUniverse.ComputeVirtualTxSigHash:input_type -> pocketuniverserpc.ComputeSigHashRequest
	2, // 1: pocketuniverserpc.PocketUniverse.ApplyExternalSignature:input_type -> pocketuniverserpc.ApplyExternalSigRequest
	1, // 2: pocketuniverserpc.PocketUniverse.ComputeVirtualTxSigHash:output_type -> pocketuniverserpc.ComputeSigHashResponse
	3, // 3: pocketuniverserpc.PocketUniverse.ApplyExternalSignature:output_type -> pocketuniverserpc.ApplyExternalSigResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pocketuniverserpc_pocketuniverse_proto_init() }
func file_pocketuniverserpc_pocketuniverse_proto_init() {
	if File_pocketuniverserpc_pocketuniverse_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pocketuniverserpc_pocketuniverse_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ComputeSigHashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pocketuniverserpc_pocketuniverse_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ComputeSigHashResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pocketuniverserpc_pocketuniverse_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ApplyExternalSigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pocketuniverserpc_pocketuniverse_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ApplyExternalSigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pocketuniverserpc_pocketuniverse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pocketuniverserpc_pocketuniverse_proto_goTypes,
		DependencyIndexes: file_pocketuniverserpc_pocketuniverse_proto_depIdxs,
		MessageInfos:      file_pocketuniverserpc_pocketuniverse_proto_msgTypes,
	}.Build()
	File_pocketuniverserpc_pocketuniverse_proto = out.File
	file_pocketuniverserpc_pocketuniverse_proto_rawDesc = nil
	file_pocketuniverserpc_pocketuniverse_proto_goTypes = nil
	file_pocketuniverserpc_pocketuniverse_proto_depIdxs = nil
}
