// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pocketuniverserpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PocketUniverseClient is the client API for PocketUniverse service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PocketUniverseClient interface {
	// ComputeVirtualTxSigHash computes the sighash that needs to be signed
	// for a virtual transaction, allowing external signing.
	ComputeVirtualTxSigHash(ctx context.Context, in *ComputeSigHashRequest, opts ...grpc.CallOption) (*ComputeSigHashResponse, error)
	// ApplyExternalSignature applies an externally-generated signature to
	// a virtual PSBT.
	ApplyExternalSignature(ctx context.Context, in *ApplyExternalSigRequest, opts ...grpc.CallOption) (*ApplyExternalSigResponse, error)
}

type pocketUniverseClient struct {
	cc grpc.ClientConnInterface
}

func NewPocketUniverseClient(cc grpc.ClientConnInterface) PocketUniverseClient {
	return &pocketUniverseClient{cc}
}

func (c *pocketUniverseClient) ComputeVirtualTxSigHash(ctx context.Context, in *ComputeSigHashRequest, opts ...grpc.CallOption) (*ComputeSigHashResponse, error) {
	out := new(ComputeSigHashResponse)
	err := c.cc.Invoke(ctx, "/pocketuniverserpc.PocketUniverse/ComputeVirtualTxSigHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pocketUniverseClient) ApplyExternalSignature(ctx context.Context, in *ApplyExternalSigRequest, opts ...grpc.CallOption) (*ApplyExternalSigResponse, error) {
	out := new(ApplyExternalSigResponse)
	err := c.cc.Invoke(ctx, "/pocketuniverserpc.PocketUniverse/ApplyExternalSignature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PocketUniverseServer is the server API for PocketUniverse service.
// All implementations must embed UnimplementedPocketUniverseServer
// for forward compatibility
type PocketUniverseServer interface {
	// ComputeVirtualTxSigHash computes the sighash that needs to be signed
	// for a virtual transaction, allowing external signing.
	ComputeVirtualTxSigHash(context.Context, *ComputeSigHashRequest) (*ComputeSigHashResponse, error)
	// ApplyExternalSignature applies an externally-generated signature to
	// a virtual PSBT.
	ApplyExternalSignature(context.Context, *ApplyExternalSigRequest) (*ApplyExternalSigResponse, error)
	mustEmbedUnimplementedPocketUniverseServer()
}

// UnimplementedPocketUniverseServer must be embedded to have forward compatible implementations.
type UnimplementedPocketUniverseServer struct {
}

func (UnimplementedPocketUniverseServer) ComputeVirtualTxSigHash(context.Context, *ComputeSigHashRequest) (*ComputeSigHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputeVirtualTxSigHash not implemented")
}
func (UnimplementedPocketUniverseServer) ApplyExternalSignature(context.Context, *ApplyExternalSigRequest) (*ApplyExternalSigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyExternalSignature not implemented")
}
func (UnimplementedPocketUniverseServer) mustEmbedUnimplementedPocketUniverseServer() {}

// UnsafePocketUniverseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PocketUniverseServer will
// result in compilation errors.
type UnsafePocketUniverseServer interface {
	mustEmbedUnimplementedPocketUniverseServer()
}

func RegisterPocketUniverseServer(s grpc.ServiceRegistrar, srv PocketUniverseServer) {
	s.RegisterService(&PocketUniverse_ServiceDesc, srv)
}

func _PocketUniverse_ComputeVirtualTxSigHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeSigHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PocketUniverseServer).ComputeVirtualTxSigHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pocketuniverserpc.PocketUniverse/ComputeVirtualTxSigHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PocketUniverseServer).ComputeVirtualTxSigHash(ctx, req.(*ComputeSigHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PocketUniverse_ApplyExternalSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyExternalSigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PocketUniverseServer).ApplyExternalSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pocketuniverserpc.PocketUniverse/ApplyExternalSignature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PocketUniverseServer).ApplyExternalSignature(ctx, req.(*ApplyExternalSigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PocketUniverse_ServiceDesc is the grpc.ServiceDesc for PocketUniverse service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PocketUniverse_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pocketuniverserpc.PocketUniverse",
	HandlerType: (*PocketUniverseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputeVirtualTxSigHash",
			Handler:    _PocketUniverse_ComputeVirtualTxSigHash_Handler,
		},
		{
			MethodName: "ApplyExternalSignature",
			Handler:    _PocketUniverse_ApplyExternalSignature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pocketuniverserpc/pocketuniverse.proto",
}
